export enum AUTH_ERROR {
  USER_ALREADY_CONFIRM_EMAIL = 'AUTH_USER_ALREADY_CONFIRM_EMAIL',
  COULDNT_FOUND_USER = 'LOGIN_COULDNT_FOUND_USER',
  USER_ALREADY_EXISTS = 'SIGN_UP_USER_ALREADY_EXISTS',
  UNCORRECT_PASSWORD_OR_LOGIN = 'LOGIN_UNCORRECT_PASSWORD_OR_LOGIN',
  UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  INVALID_CODE = 'INVALID_CODE',
  INVALID_PINCODE = 'INVALID_PINCODE',
}
